name: Lint
on: [push]


jobs:
  python:
    name: python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: ricardochaves/python-lint@v1.1.0
        with:
          python-root-list: "scrape.py"
          use-pycodestyle: false
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: false
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install eslint
      run: npm install eslint
    - name: eslint
      uses: icrawl/action-eslint@v1
      with:
        custom-glob: timeline.js