name: Lint
on: [push]


jobs:
  build:
    name: python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: ricardochaves/python-lint@v1.1.0
        with:
          python-root-list: "scrape.py"
          extra-pylint-options: "--rcfile=.pylintrc"